server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: ${DB_LOCAL_R2DBC_URL}
    username: ${DB_LOCAL_USERNAME}
    password: ${DB_LOCAL_PASSWORD}
  sql:
    init:
      mode: always
