server:
  port: ${SERVER_PORT}


spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:mysql://${DB_LOCAL_R2DBC_URL}:${DB_LOCAL_PORT}/${DB_LOCAL_NAME}
    username: ${DB_LOCAL_USERNAME}
    password: ${DB_LOCAL_PASSWORD}
  sql:
    init:
      mode: never

security:
  jwt:
    secret: ${JWT_PASSWORD}
    expiration:
      minutes: ${JWT_EXPIRATION_MINUTES}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.reactive: DEBUG
    io.r2dbc.spi: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.github.cristhianm30.heikoh: DEBUG
